/**
 * MediaPage — visual gallery for images and videos generated by Clawksis tools.
 *
 * Consumes /api/gallery/* endpoints (implemented in clawk_cli/web_server.py).
 * Files served by /media/file/{id} (also in web_server.py, outside /api/ so
 * <img src> works without needing the session token).
 *
 * Layout:
 *   [Header: stats badges + refresh]
 *   [Filter bar: type, date range, search, model]
 *   [Grid: responsive tiles with hover actions]
 *   [Lightbox modal: full view + 5 action buttons]
 *
 * Persistence backed by media_generations table (see tools/media_persistence.py).
 */

import { useCallback, useEffect, useMemo, useState } from "react";
import {
  Image as ImageIcon,
  Video,
  Search,
  RefreshCw,
  Download,
  Trash2,
  Copy,
  Repeat,
  Sparkles,
  Eye,
  X,
  Calendar,
  HardDrive,
} from "lucide-react";
import { api } from "@/lib/api";
import type {
  MediaItem,
  MediaListFilters,
  MediaStats,
} from "@/lib/api";
import { Card, CardContent } from "@nous-research/ui/ui/components/card";
import { Button } from "@nous-research/ui/ui/components/button";
import { Spinner } from "@nous-research/ui/ui/components/spinner";
import { usePageHeader } from "@/contexts/usePageHeader";
import { cn } from "@/lib/utils";
import { PluginSlot } from "@/plugins";

const PAGE_SIZE = 60;

function formatBytes(bytes: number | null | undefined): string {
  if (!bytes) return "—";
  const kb = bytes / 1024;
  if (kb < 1024) return `${kb.toFixed(1)} KB`;
  const mb = kb / 1024;
  if (mb < 1024) return `${mb.toFixed(1)} MB`;
  return `${(mb / 1024).toFixed(2)} GB`;
}

function formatDate(unix: number): string {
  try {
    return new Date(unix * 1000).toLocaleString(undefined, {
      year: "numeric",
      month: "short",
      day: "numeric",
      hour: "2-digit",
      minute: "2-digit",
    });
  } catch {
    return "—";
  }
}

function formatDateShort(unix: number): string {
  try {
    return new Date(unix * 1000).toLocaleDateString(undefined, {
      month: "short",
      day: "numeric",
    });
  } catch {
    return "—";
  }
}

function truncatePrompt(prompt: string | null | undefined, max = 80): string {
  if (!prompt) return "";
  return prompt.length <= max ? prompt : prompt.slice(0, max - 1) + "…";
}

function mediaUrl(item: MediaItem): string {
  return `/media/file/${item.id}`;
}

// ---------------------------------------------------------------------------
// Filter bar
// ---------------------------------------------------------------------------

interface FilterBarProps {
  filters: MediaListFilters;
  onChange: (patch: Partial<MediaListFilters>) => void;
  onClear: () => void;
}

function FilterBar({ filters, onChange, onClear }: FilterBarProps) {
  const hasFilters =
    !!filters.media_type ||
    !!filters.search ||
    !!filters.model ||
    filters.date_from !== undefined ||
    filters.date_to !== undefined ||
    filters.min_size !== undefined ||
    filters.max_size !== undefined;

  return (
    <div className="flex flex-wrap items-center gap-2 rounded-md border border-border bg-surface-1 p-3">
      <div className="flex items-center gap-1">
        <Button
          size="sm"
          ghost={!!filters.media_type}
          onClick={() => onChange({ media_type: undefined })}
        >
          All
        </Button>
        <Button
          size="sm"
          ghost={filters.media_type !== "image"}
          onClick={() => onChange({ media_type: "image" })}
        >
          <ImageIcon className="mr-1 h-3.5 w-3.5" />
          Images
        </Button>
        <Button
          size="sm"
          ghost={filters.media_type !== "video"}
          onClick={() => onChange({ media_type: "video" })}
        >
          <Video className="mr-1 h-3.5 w-3.5" />
          Videos
        </Button>
      </div>

      <div className="mx-2 h-6 w-px bg-border" />

      <div className="relative flex-1 min-w-[180px] max-w-[320px]">
        <Search className="pointer-events-none absolute left-2 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
        <input
          type="text"
          placeholder="Search prompt…"
          value={filters.search ?? ""}
          onChange={(e) => onChange({ search: e.target.value || undefined })}
          className="w-full rounded-md border border-border bg-surface-2 py-1.5 pl-8 pr-2 text-sm outline-none focus:border-primary"
        />
      </div>

      <input
        type="date"
        value={
          filters.date_from
            ? new Date(filters.date_from * 1000).toISOString().slice(0, 10)
            : ""
        }
        onChange={(e) => {
          const v = e.target.value
            ? new Date(e.target.value).getTime() / 1000
            : undefined;
          onChange({ date_from: v });
        }}
        className="rounded-md border border-border bg-surface-2 px-2 py-1.5 text-sm outline-none focus:border-primary"
        title="Date from"
      />
      <span className="text-xs text-muted-foreground">→</span>
      <input
        type="date"
        value={
          filters.date_to
            ? new Date(filters.date_to * 1000).toISOString().slice(0, 10)
            : ""
        }
        onChange={(e) => {
          const v = e.target.value
            ? new Date(e.target.value).getTime() / 1000 + 86400
            : undefined;
          onChange({ date_to: v });
        }}
        className="rounded-md border border-border bg-surface-2 px-2 py-1.5 text-sm outline-none focus:border-primary"
        title="Date to"
      />

      <input
        type="text"
        placeholder="Model"
        value={filters.model ?? ""}
        onChange={(e) => onChange({ model: e.target.value || undefined })}
        className="w-32 rounded-md border border-border bg-surface-2 px-2 py-1.5 text-sm outline-none focus:border-primary"
        title="Filter by model"
      />

      {hasFilters && (
        <Button size="sm" ghost onClick={onClear}>
          <X className="mr-1 h-3.5 w-3.5" />
          Clear
        </Button>
      )}
    </div>
  );
}

// ---------------------------------------------------------------------------
// Media tile
// ---------------------------------------------------------------------------

function MediaTile({
  item,
  onClick,
}: {
  item: MediaItem;
  onClick: () => void;
}) {
  const isVideo = item.media_type === "video";
  const isExpired = item.status === "expired";
  const isMissing = item.status === "missing";

  return (
    <button
      type="button"
      onClick={onClick}
      className={cn(
        "group relative aspect-square overflow-hidden rounded-md border border-border bg-surface-1",
        "transition-all hover:border-primary hover:shadow-md",
        "focus-visible:border-primary focus-visible:outline-none",
      )}
      title={truncatePrompt(item.prompt, 140)}
    >
      {isExpired || isMissing ? (
        <div className="flex h-full w-full flex-col items-center justify-center gap-1 bg-surface-0 text-muted-foreground">
          <ImageIcon className="h-8 w-8 opacity-40" />
          <span className="text-xs">
            {isExpired ? "Expired" : "Missing"}
          </span>
        </div>
      ) : isVideo ? (
        <>
          <video
            src={mediaUrl(item)}
            className="h-full w-full object-cover"
            preload="metadata"
            muted
          />
          <div className="absolute right-1.5 top-1.5 rounded bg-black/70 px-1.5 py-0.5">
            <Video className="h-3 w-3 text-white" />
          </div>
        </>
      ) : (
        <img
          src={mediaUrl(item)}
          alt={truncatePrompt(item.prompt, 40) || "Generated media"}
          loading="lazy"
          className="h-full w-full object-cover"
        />
      )}

      <div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/70 to-transparent p-2 opacity-0 transition-opacity group-hover:opacity-100">
        <p className="line-clamp-2 text-[10px] leading-tight text-white">
          {truncatePrompt(item.prompt, 60) || "No prompt"}
        </p>
        <p className="mt-1 text-[9px] text-white/70">
          {formatDateShort(item.created_at)} · {formatBytes(item.file_size_bytes)}
        </p>
      </div>
    </button>
  );
}

// ---------------------------------------------------------------------------
// Lightbox modal
// ---------------------------------------------------------------------------

function Lightbox({
  item,
  onClose,
  onDelete,
}: {
  item: MediaItem;
  onClose: () => void;
  onDelete: (id: string) => Promise<void>;
}) {
  const [deleting, setDeleting] = useState(false);
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    const handler = (e: KeyboardEvent) => {
      if (e.key === "Escape") onClose();
    };
    window.addEventListener("keydown", handler);
    return () => window.removeEventListener("keydown", handler);
  }, [onClose]);

  const handleCopyPath = useCallback(async () => {
    try {
      await navigator.clipboard.writeText(item.file_path);
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    } catch (e) {
      console.warn("Copy failed", e);
    }
  }, [item.file_path]);

  const handleDelete = useCallback(async () => {
    if (!confirm("Delete this media permanently? The file will be removed from disk.")) {
      return;
    }
    setDeleting(true);
    try {
      await onDelete(item.id);
      onClose();
    } catch (e) {
      console.error("Delete failed", e);
      alert("Failed to delete. See console.");
    } finally {
      setDeleting(false);
    }
  }, [item.id, onDelete, onClose]);

  const isVideo = item.media_type === "video";
  const isBroken = item.status !== "ready";

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 p-4"
      onClick={onClose}
    >
      <div
        className="relative flex max-h-[90vh] w-full max-w-6xl flex-col gap-4 overflow-hidden rounded-lg bg-surface-2 p-4 md:flex-row"
        onClick={(e) => e.stopPropagation()}
      >
        <button
          type="button"
          onClick={onClose}
          className="absolute right-3 top-3 z-10 rounded-full bg-surface-1 p-1.5 hover:bg-surface-0"
          aria-label="Close"
        >
          <X className="h-4 w-4" />
        </button>

        <div className="flex flex-1 items-center justify-center overflow-hidden rounded bg-surface-0">
          {isBroken ? (
            <div className="flex flex-col items-center gap-2 p-8 text-muted-foreground">
              <ImageIcon className="h-16 w-16 opacity-30" />
              <p className="text-sm">Media is {item.status}</p>
              {item.original_url && (
                <p className="text-xs">Original URL: {item.original_url}</p>
              )}
            </div>
          ) : isVideo ? (
            <video
              src={mediaUrl(item)}
              controls
              className="max-h-full max-w-full"
            />
          ) : (
            <img
              src={mediaUrl(item)}
              alt={item.prompt ?? "Generated media"}
              className="max-h-full max-w-full object-contain"
            />
          )}
        </div>

        <div className="flex w-full flex-col gap-3 md:w-80 md:flex-shrink-0">
          <div>
            <h3 className="text-sm font-medium">Prompt</h3>
            <p className="mt-1 text-xs text-text-secondary">
              {item.prompt ?? "No prompt recorded"}
            </p>
          </div>

          <div className="grid grid-cols-2 gap-2 text-xs">
            <div>
              <span className="text-muted-foreground">Type</span>
              <p>{item.media_type}</p>
            </div>
            <div>
              <span className="text-muted-foreground">Size</span>
              <p>{formatBytes(item.file_size_bytes)}</p>
            </div>
            {item.width && item.height && (
              <div>
                <span className="text-muted-foreground">Dims</span>
                <p>{item.width}×{item.height}</p>
              </div>
            )}
            <div>
              <span className="text-muted-foreground">Model</span>
              <p className="truncate">{item.model ?? "—"}</p>
            </div>
            <div>
              <span className="text-muted-foreground">Provider</span>
              <p>{item.provider ?? "—"}</p>
            </div>
            <div>
              <span className="text-muted-foreground">Created</span>
              <p>{formatDate(item.created_at)}</p>
            </div>
          </div>

          <div className="border-t border-border pt-3">
            <p className="mb-2 text-xs font-medium text-muted-foreground">Actions</p>
            <div className="flex flex-col gap-2">
              <a
                href={mediaUrl(item)}
                download
                className="inline-flex items-center gap-2 rounded-md border border-border bg-surface-1 px-3 py-2 text-xs hover:bg-surface-0"
              >
                <Download className="h-3.5 w-3.5" />
                Download
              </a>

              <button
                type="button"
                onClick={handleCopyPath}
                className="inline-flex items-center gap-2 rounded-md border border-border bg-surface-1 px-3 py-2 text-xs hover:bg-surface-0"
              >
                <Copy className="h-3.5 w-3.5" />
                {copied ? "Copied!" : "Copy path"}
              </button>

              <div className="border-t border-border pt-2">
                <p className="mb-1.5 text-[10px] font-medium uppercase tracking-wide text-muted-foreground">
                  Use as reference in chat
                </p>
                <div className="flex flex-col gap-1.5">
                  <button
                    type="button"
                    disabled
                    title="Coming soon"
                    className="inline-flex items-center gap-2 rounded-md border border-border bg-surface-1 px-3 py-2 text-xs text-muted-foreground opacity-60"
                  >
                    <Repeat className="h-3.5 w-3.5" />
                    Re-attach in next message
                  </button>
                  <button
                    type="button"
                    disabled
                    title="Coming soon"
                    className="inline-flex items-center gap-2 rounded-md border border-border bg-surface-1 px-3 py-2 text-xs text-muted-foreground opacity-60"
                  >
                    <Sparkles className="h-3.5 w-3.5" />
                    Re-generate variation
                  </button>
                  <button
                    type="button"
                    disabled
                    title="Coming soon"
                    className="inline-flex items-center gap-2 rounded-md border border-border bg-surface-1 px-3 py-2 text-xs text-muted-foreground opacity-60"
                  >
                    <Eye className="h-3.5 w-3.5" />
                    Send as visual context
                  </button>
                </div>
              </div>

              <button
                type="button"
                onClick={handleDelete}
                disabled={deleting}
                className="mt-2 inline-flex items-center gap-2 rounded-md border border-destructive/40 bg-destructive/10 px-3 py-2 text-xs text-destructive hover:bg-destructive/20 disabled:opacity-50"
              >
                <Trash2 className="h-3.5 w-3.5" />
                {deleting ? "Deleting…" : "Delete permanently"}
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Page
// ---------------------------------------------------------------------------

export default function MediaPage() {
  const { setEnd } = usePageHeader();
  const [items, setItems] = useState<MediaItem[]>([]);
  const [stats, setStats] = useState<MediaStats | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [total, setTotal] = useState(0);
  const [hasMore, setHasMore] = useState(false);
  const [filters, setFilters] = useState<MediaListFilters>({ limit: PAGE_SIZE, offset: 0 });
  const [lightboxItem, setLightboxItem] = useState<MediaItem | null>(null);

  const activeFilters = useMemo(() => ({ ...filters, limit: PAGE_SIZE }), [filters]);

  const loadData = useCallback(
    async (opts: { append?: boolean; offset?: number } = {}) => {
      const { append = false, offset } = opts;
      setLoading(true);
      setError(null);
      try {
        const queryFilters = { ...activeFilters, offset: offset ?? 0 };
        const [listRes, statsRes] = await Promise.all([
          api.getGalleryMedia(queryFilters),
          append ? Promise.resolve(null) : api.getGalleryStats(),
        ]);
        setItems((prev) => (append ? [...prev, ...listRes.items] : listRes.items));
        setTotal(listRes.total);
        setHasMore(listRes.has_more);
        if (statsRes) setStats(statsRes);
      } catch (e) {
        console.error("Failed to load gallery", e);
        setError(e instanceof Error ? e.message : String(e));
      } finally {
        setLoading(false);
      }
    },
    [activeFilters],
  );

  useEffect(() => {
    loadData();
  }, [loadData]);

  const handleFilterChange = useCallback((patch: Partial<MediaListFilters>) => {
    setFilters((prev) => ({ ...prev, ...patch, offset: 0 }));
  }, []);

  const handleClearFilters = useCallback(() => {
    setFilters({ limit: PAGE_SIZE, offset: 0 });
  }, []);

  const handleLoadMore = useCallback(() => {
    loadData({ append: true, offset: items.length });
  }, [items.length, loadData]);

  const handleDelete = useCallback(async (id: string) => {
    await api.deleteGalleryMedia(id);
    setItems((prev) => prev.filter((it) => it.id !== id));
    setTotal((prev) => Math.max(0, prev - 1));
    if (stats) {
      const removed = items.find((it) => it.id === id);
      if (removed) {
        setStats({
          ...stats,
          total_images: removed.media_type === "image" ? stats.total_images - 1 : stats.total_images,
          total_videos: removed.media_type === "video" ? stats.total_videos - 1 : stats.total_videos,
        });
      }
    }
  }, [items, stats]);

  useEffect(() => {
    setEnd(
      <Button size="sm" ghost onClick={() => loadData()} disabled={loading}>
        <RefreshCw className={cn("mr-1 h-3.5 w-3.5", loading && "animate-spin")} />
        Refresh
      </Button>,
    );
    return () => setEnd(null);
  }, [loadData, loading, setEnd]);

  return (
    <div className={cn("flex min-h-0 w-full min-w-0 flex-1 flex-col gap-4", "pt-1 sm:pt-2")}>
      <PluginSlot name="media:top" />

      {stats && (
        <div className="grid grid-cols-2 gap-2 sm:grid-cols-4">
          <Card className="rounded-md">
            <CardContent className="flex items-center gap-3 py-3">
              <ImageIcon className="h-5 w-5 text-muted-foreground" />
              <div>
                <p className="text-lg font-medium">{stats.total_images}</p>
                <p className="text-xs text-muted-foreground">Images</p>
              </div>
            </CardContent>
          </Card>
          <Card className="rounded-md">
            <CardContent className="flex items-center gap-3 py-3">
              <Video className="h-5 w-5 text-muted-foreground" />
              <div>
                <p className="text-lg font-medium">{stats.total_videos}</p>
                <p className="text-xs text-muted-foreground">Videos</p>
              </div>
            </CardContent>
          </Card>
          <Card className="rounded-md">
            <CardContent className="flex items-center gap-3 py-3">
              <HardDrive className="h-5 w-5 text-muted-foreground" />
              <div>
                <p className="text-lg font-medium">{formatBytes(stats.total_size_bytes)}</p>
                <p className="text-xs text-muted-foreground">Total size</p>
              </div>
            </CardContent>
          </Card>
          <Card className="rounded-md">
            <CardContent className="flex items-center gap-3 py-3">
              <Calendar className="h-5 w-5 text-muted-foreground" />
              <div>
                <p className="text-lg font-medium">{stats.last_7_days}</p>
                <p className="text-xs text-muted-foreground">Last 7 days</p>
              </div>
            </CardContent>
          </Card>
        </div>
      )}

      <FilterBar
        filters={filters}
        onChange={handleFilterChange}
        onClear={handleClearFilters}
      />

      {error && (
        <div className="rounded-md border border-destructive/40 bg-destructive/10 p-3 text-sm text-destructive">
          Failed to load gallery: {error}
        </div>
      )}

      {loading && items.length === 0 ? (
        <div className="flex flex-1 items-center justify-center">
          <Spinner />
        </div>
      ) : items.length === 0 ? (
        <div className="flex flex-1 flex-col items-center justify-center gap-2 text-muted-foreground">
          <ImageIcon className="h-12 w-12 opacity-30" />
          <p className="text-sm">No media yet</p>
          <p className="text-xs">
            Generate an image with the <code className="rounded bg-surface-1 px-1">image_generate</code> tool to see it here.
          </p>
        </div>
      ) : (
        <>
          <div className="grid grid-cols-2 gap-3 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 xl:grid-cols-6">
            {items.map((item) => (
              <MediaTile
                key={item.id}
                item={item}
                onClick={() => setLightboxItem(item)}
              />
            ))}
          </div>

          {hasMore && (
            <div className="flex justify-center py-2">
              <Button
                ghost
                onClick={handleLoadMore}
                disabled={loading}
              >
                {loading ? <Spinner className="mr-2 h-3 w-3" /> : null}
                Load more ({total - items.length} remaining)
              </Button>
            </div>
          )}

          <div className="pb-4 text-center text-xs text-muted-foreground">
            Showing {items.length} of {total}
          </div>
        </>
      )}

      {lightboxItem && (
        <Lightbox
          item={lightboxItem}
          onClose={() => setLightboxItem(null)}
          onDelete={handleDelete}
        />
      )}

      <PluginSlot name="media:bottom" />
    </div>
  );
}
